// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: 4

package helloworld

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Newdata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Newdata) Reset() {
	*x = Newdata{}
	if protoimpl.UnsafeEnabled {
		mi := &file__4_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Newdata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Newdata) ProtoMessage() {}

func (x *Newdata) ProtoReflect() protoreflect.Message {
	mi := &file__4_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Newdata.ProtoReflect.Descriptor instead.
func (*Newdata) Descriptor() ([]byte, []int) {
	return file__4_rawDescGZIP(), []int{0}
}

func (x *Newdata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File__4 protoreflect.FileDescriptor

var file__4_rawDesc = []byte{
	0x0a, 0x01, 0x34, 0x12, 0x0a, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22,
	0x1d, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x25,
	0x5a, 0x23, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file__4_rawDescOnce sync.Once
	file__4_rawDescData = file__4_rawDesc
)

func file__4_rawDescGZIP() []byte {
	file__4_rawDescOnce.Do(func() {
		file__4_rawDescData = protoimpl.X.CompressGZIP(file__4_rawDescData)
	})
	return file__4_rawDescData
}

var file__4_msgTypes = make([]protoimpl.MessageInfo, 1)
var file__4_goTypes = []interface{}{
	(*Newdata)(nil), // 0: helloworld.newdata
}
var file__4_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file__4_init() }
func file__4_init() {
	if File__4 != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file__4_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Newdata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file__4_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file__4_goTypes,
		DependencyIndexes: file__4_depIdxs,
		MessageInfos:      file__4_msgTypes,
	}.Build()
	File__4 = out.File
	file__4_rawDesc = nil
	file__4_goTypes = nil
	file__4_depIdxs = nil
}
